author: GitHub User
name: Ha Yun Yang

title: "Ha Yun Yang : Portfolio"
description: >- # this means to ignore newlines until "baseurl:"
  메이플스토리의 세계관 위에서 새로운 재미를 설계하는 기획자,
  <br><font size=5>양하윤</font>입니다.
  <br>
  <br>
  <br><font size=6>관심 분야</font>
  <br>메이플스토리, 메이플스토리 월드, 메이플스토리 IP, MMORPG
  <br>
  <br>
  <br><font size=6>관심 직무</font>
  <br>IP 활용, 콘텐츠 기획, 전투 디자인, 레벨 디자인

email: iruna2122@kakao.com

# social links
#twitter_username: anxhe_
#github_username:  anxhe
# rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: 하윤-양-50b508376
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%b-%d"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# baseurl: http://127.0.0.1:4000
header_pages:
  - index.md
  - blog.md

# Config section the home


# Build settings
markdown: kramdown

jekyll-theme-experiment:
  about:
    avatar : https://avatar.maplestory.nexon.com/Character/180/JGAEDLDADDENPPNGCKJJPCKJOMDKNENHCGPLONACJAOABMAANPPBAOHHNKGDFCKMIADOMBFEJMAGPGHEGOPNPPJMCMNGKNJENLGOGMMPILLJGGDMIBDNDDGOPNINENGFEDACCAEAAPCAAFGMJBDGPLGLEJPHNCKJDKEBMOOAKLHHLLGDJOFCELCLJAICCLPIBNNBDGNPPHIGJGMBDNCOLFLBLJCINABGIBGPGFFGLCNMCKINOLENMBBGJGJFILEE.png

  portfolio:
    title: Portfolio
    projects:

      - name: <메이플 유니온 체스> 기획/개발
        #link: 
        #github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/maple-union-chess-thumbnail.png

      - name: 한국게임학회 춘계 논문 발표
        #link: 
        #github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/mapleworld_ip_paper.png

      - name: <메이플스토리> IP 경험
        #link: 
        #github: https://github.com/anxhe/jekyll-theme-experiment
        img_relative_url: /assets/example.png

  tools:
    title: ABOUT ME
    icons:
      #- relative_url: /assets/icons/bitbucket/bitbucket-original.svg
      #- relative_url: /assets/icons/heroku/heroku-original.svg
      #- relative_url: /assets/icons/git/git-original.svg
      #- relative_url: /assets/icons/express/express-original.svg
      #- relative_url: /assets/icons/angularjs/angularjs-original.svg

exclude:
  - Gemfile
  - Gemfile.lock
